### ISSUE TITLE
Bug on navigator.geolocation.getCurrentPosition() 

### ISSUE THREAD

**Issue by JonathanAriass** [Arquisoft/lomap_es5c#19]
When using other browsers apart from Firefox the navigator.geolocation.getCurrentPosition() bugs and don't ask againg for permissions to use the location. How should be the cache of the browsers treated?
![The codefile.](https://github.com/Arquisoft/lomap_es5c/blob/develop/webapp/src/components/UI/NotLoggedText.js)

**Comment by gitblanc** [comment]
corrected

**Comment by gitblanc** [comment]
Might be a possible solution in the backend with Node.js -> https://stackoverflow.com/questions/65528622/how-to-specify-a-cache-control-header-for-index-html-in-create-react-app
